parameters:
#    loicolas_main.example.class: Loicolas\Bundle\MainBundle\Example

services:
    loicolas_main.work_experience_manager:
        class: Loicolas\Bundle\MainBundle\Entity\WorkExperienceManager
        arguments: [Loicolas\Bundle\MainBundle\Entity\WorkExperience, @doctrine]

    loicolas_main.company_manager:
        class: Loicolas\Bundle\MainBundle\Entity\CompanyManager
        arguments: [Loicolas\Bundle\MainBundle\Entity\Company, @doctrine]
        
    loicolas_main.diploma_manager:
        class: Loicolas\Bundle\MainBundle\Entity\DiplomaManager
        arguments: [Loicolas\Bundle\MainBundle\Entity\Diploma, @doctrine]
