sonata_news:
    title:        Sonata Project
    link:         http://sonata-project.org
    description:  Cool bundles on top of Symfony2
    salt:         'secureToken'
    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.collection

    comment:
        notification:
            emails:   [loicolas@gmail.com]
            from:     no-reply@loicolas.fr
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'