<?php

namespace Loicolas\Bundle\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkExperienceRepository extends EntityRepository
{
}
